frontend仕様書の作成
oginoshikibu/wikipedia-golf pull request #4
Opened 2023-11-28 15:53 UTC by kodomodragon

2023-11-28 16:15 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +        -   機能：Wordるを作っている会社の他のゲームの告知プルダウンが開く。
typo ?
```suggestion
        -   機能：Wordleを作っている会社の他のゲームの告知プルダウンが開く。
```

2023-11-28 16:18 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        -   機能：Wordるを作っている会社の他のゲームの告知プルダウンが開く。
修正しました。ありがとうございます。

2023-11-29 06:32 UTC, oginoshikibu reviewed
内容自体はとても良いです。ありがとうございます！
ただ、文書的にとても読みづらい構造になってしまっているので、指摘した点を全体にわたって修正をお願いしたいです🙇
こういった、インデントやスペース、書くこと書かないこと、文体の変更はコーディングでもとても生きてくるので、今のうちに練習しちゃいましょう。
何かわからないこと・議論したいことがあれば、遠慮なくreplyしてください

2023-11-29 06:32 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +        - 画面遷移後。
- [ ] 「次の画面」のように指示語を含むと、何を指しているのかわかりません。出来るだけ一行単体でわかるとよいです。
- [ ] 画面別に項目を区切ってほしいです。なので、別画面の説明はそれぞれ見出しをつけるのはどうでしょうか。
- [ ] 「機能：」は不要な気がします。markdownを書くコツとして、「同じ情報を同じレベルで揃えて、説明をmarkdownの構造に任せる」ということがあります。今回の場合、
```markdown
- foo ボタン
  1.  fooとalartが出る

- bar ボタン
  1. barとalartが出る
  2. 閉じると画面hogeへ遷移
```
のようにインデント内に機能を書けば、「機能：」がなくても内容が理解できます。


```suggestion 
- How to Play ボタン
  1.  ゲームプレイ画面へ遷移
# ゲームプレイ画面
- index pageより遷移した場合、遊び方のポップアップを表示
```

2023-11-29 06:32 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +- 初期画面の構成
#の後は半角スペースを入れましょう。
仕様書なので「開く」という動作ではなく、ページタイトルに当たるような名詞を見出しにした方が良いかと思います。
```suggestion
# index page
```

2023-11-29 06:32 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +        - ボタン（？）：画面中央に遊び方のポップアップが出現する。
仕様書なので、出来るだけ言い切りたいです。
未定な場合であれば、ちゃんと未定である理由も残しましょう。
今回の場合は「もしかしたら変わるかも、変えてもよい」程度の話だと思うので、言い切ってよいと思います。
問題が生じた段階で相談しましょう

```suggestion
        - ボタン：画面中央に遊び方のポップアップが出現する。
```

2023-11-29 15:31 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        - ボタン（？）：画面中央に遊び方のポップアップが出現する。
ポップアップという現象につける名称をボタンとしてよいか分からなかったため、（？）を付けました。後で相談しようと思って忘れていました。今後は未定である理由も明記するようにします。指摘をありがとうございます。

2023-11-29 15:54 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +        - ボタン（？）：画面中央に遊び方のポップアップが出現する。
これは「ボタンを押す」→ポップアップということですか？

2023-11-29 15:56 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        - 画面遷移後。
アドバイスを下さり、ありがとうございます。
・画面ごとに見出しを付けて区別する。
・情報の階層とMarkdownの構造を対応させる。
以上の二点について承知しました。

2023-11-29 15:59 UTC, kodomodragon commented on docs/frontend/frontend.md
> +- 初期画面の構成
変更して下さり、ありがとうございます。

2023-11-29 16:01 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        - ボタン（？）：画面中央に遊び方のポップアップが出現する。
いいえ。別の画面から現在の画面に遷移する際に、強制的に表示されました。別の画面内のボタンを押すと、現在の画面に遷移し、その際にポップアップも表示されるという意味です。

2023-11-29 16:13 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +        - ボタン（？）：画面中央に遊び方のポップアップが出現する。
なるほど。ややこしいですね。
実装するときを考えてみると。「ボタン」という機能ではなく「ポップアップ」という機能を作成して、遷移時にフラグを渡して条件分岐（特定のページから飛んできた場合表示）などする形になると思います。
少し全体像がつかめていない部分があり、修正方法はお任せしようと思いますが、どうしようか困ったら教えてください。

2023-12-04 15:27 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        - ボタン（？）：画面中央に遊び方のポップアップが出現する。
- ボタン
  1. ......
  2. ......
- ポップアップ
  1. ……
 上記のように、ボタンとポップアップを同じ階層としましたことを報告いたします。よろしくお願いします。

2023-12-10 01:41 UTC, oginoshikibu requested changes
めちゃめちゃ読みやすくなりました！！おかげさまでレビューも爆速で進められました。
一点、ファイル名についてなのですが、docs/02.frontend/README.md に変更をお願いしてもよいでしょうか？？

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +  1. #How to play画面へ遷移
ポップアップと画面が混同している状態なので統一したいです
```suggestion
  1. ゲームプレイ画面へ遷移し、How to playポップアップを表示
```

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +  1. #ゲームプレイ画面へ遷移
`#`はh1タグをつけるための命令なので、表示する必要はないと思います。
一応こんな感じでそこへのリンクをつけることもできます（多分……）

```suggestion
  1. [How to play画面](#How to play画面)へ遷移
- Log in ボタン
  1. [ログイン画面](#ログイン画面)へ遷移
- Play ボタン
  1. [ゲームプレイ画面](#ゲームプレイ画面)へ遷移
```

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +  1. 右上のバツ印またはポップアップの外部をクリックで#ゲームプレイ画面へ遷移。
ポップアップ自体は画面ではないので、h1タグにしたくないな～というきもちになっています。
変更方法としては
1. 普通に機能とみなして、ゲームプレイ画面の中に入れる
2. h2タグをつける（こちらの場合も記載場所はゲームプレイ画面の下がよいと思います）

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +- 日記形式でその日の問題のヒントを掲載。
今回はこの画面必要ないかな（毎日僕らも管理しないといけない or 問題を解析するコードを作らなきゃなので）と思うので消してしまってよいかなと思います
また削除に伴って上の方の遷移についての機能・説明もついでに消しちゃってください！！

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +- ゲームへの課金が出来る。プレイ回数制限がなくなる。
こちらもヒント画面と同様に、消してしまってよいと思います

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +     1. create accoutn ボタン
typo?
```suggestion
     1. create account ボタン
```

2023-12-10 01:41 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +  1. Wordleの製作会社の他製品の広告が開く。
この文章はwikipedia golfの仕様書なので、これは必要ないかなと思います

2023-12-10 01:49 UTC, kodomodragon commented on docs/frontend/frontend.md
> +  1. #How to play画面へ遷移
指摘下さり、ありがとうございます。私も全く同意します。後日改めて見ると階層がおかしい事に気が付きましたが、コンフリクトが起こるのを恐れて変更していませんでした。

2023-12-10 01:53 UTC, kodomodragon commented on docs/frontend/frontend.md
> +  1. #ゲームプレイ画面へ遷移
ボタンに対応する遷移画面を明快に伝える方法が思いつきませんでした。今後は川原君の記法で統一します。よろしくお願いします。

2023-12-10 01:55 UTC, kodomodragon commented on docs/frontend/frontend.md
> +  1. 右上のバツ印またはポップアップの外部をクリックで#ゲームプレイ画面へ遷移。
1. ポップアップをゲームプレイ画面の階層に機能として組み込む。
2. h2タグをつける。
ことについて、承知しました。ありがとうございます。

2023-12-10 01:56 UTC, kodomodragon commented on docs/frontend/frontend.md
> +- 日記形式でその日の問題のヒントを掲載。
承知しました。ありがとうございます。

2023-12-10 01:56 UTC, kodomodragon commented on docs/frontend/frontend.md
> +- ゲームへの課金が出来る。プレイ回数制限がなくなる。
承知しました。ありがとうございます。

2023-12-10 01:56 UTC, kodomodragon commented on docs/frontend/frontend.md
> +     1. create accoutn ボタン
ありがとうございます。

2023-12-10 01:56 UTC, kodomodragon commented on docs/frontend/frontend.md
> +  1. Wordleの製作会社の他製品の広告が開く。
承知しました。ありがとうございます。

2023-12-10 03:36 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +  1. #ゲームプレイ画面へ遷移
なんか空白はハイフンにしなきゃらしいです
https://qiita.com/hennin/items/7ee58dd7d7c013a23be7

2023-12-23 03:13 UTC, oginoshikibu requested changes
ありがとうございます！！！一点のみ確認お願いします！！
もう修正点はないと思うので、フォルダ、ファイル名の変更もしちゃってください。

2023-12-23 03:13 UTC, oginoshikibu commented on docs/frontend/frontend.md
> +        1. パスワードが６文字以上のとき、メールアドレスに紐づいたアカウントを作成する。
この文面だと「メールアドレスを入力した場合は必ずアカウント作成へ誘導する」のように見受けられるのですが、あっていますか？？

2023-12-23 11:36 UTC, kodomodragon reviewed
コードを訂正するための入力欄とコメントを残すための入力欄を間違えました。すみません。

2023-12-23 11:36 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        1. 空欄_Login-mail_pass-bに文字列が入力されているが、その文字列に半角英数字以外の文字が含まれるとき、「ある種の複雑な文字は私たちのパスワードでは許容されていません」という文章を表示する。
空欄_Login-mail_pass-aと空欄_Login-mail_pass-bの階層を一つ下げるべきでした。

2023-12-23 11:37 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        1. 空欄_Login-mail_pass-bに文字列が入力されているが、その文字列に半角英数字以外の文字が含まれるとき、「ある種の複雑な文字は私たちのパスワードでは許容されていません」という文章を表示する。
選択範囲が広すぎて、とても見ずらくなってしまいました。申し訳ないです。

2023-12-23 11:42 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        1. パスワードが６文字以上のとき、メールアドレスに紐づいたアカウントを作成する。
間違っておりました。アカウント作成、ログインの構造に分岐がありました。修正したものをpushしました。よろしくお願いします。

2023-12-23 11:43 UTC, kodomodragon commented on docs/frontend/frontend.md
> +        1. 空欄_Login-mail_pass-bに文字列が入力されているが、その文字列に半角英数字以外の文字が含まれるとき、「ある種の複雑な文字は私たちのパスワードでは許容されていません」という文章を表示する。
Hide Commentは誤りです。Hide commentを選択すると、レビューを含むすべてのコメントが隠されてしまいました。

2023-12-23 11:46 UTC, kodomodragon commented
Change the login-gamen structure.

2023-12-23 22:36 UTC, oginoshikibu approved these changes
ありがとうございます！！
ちょこちょこ追加＆変更しちゃったので、ざっと確認してからマージお願いします！！
マージしたらブランチも消しちゃってください。

2023-12-23 22:42 UTC, oginoshikibu commented
ちなみにコミット頻度は↑ぐらい細かくするとよいと思います

2024-01-07 00:58 UTC, kodomodragon commented
> ちなみにコミット頻度は↑ぐらい細かくするとよいと思います

ありがとうございます。今後は細かくコミットを意識していきます。
よろしくお願いします。

2024-01-07 01:01 UTC, merged